#This file is an example of an environment file for defining the isolated
#networks and related parameters.
resource_registry:
  # Network Interface templates to use (these files must exist)
  OS::TripleO::Compute::Net::SoftwareConfig:
        /home/stack/templates/nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig:
        /home/stack/templates/nic-configs/control.yaml
  OS::TripleO::CephStorage::Net::SoftwareConfig:
        /home/stack/templates/nic-configs/ceph-storage.yaml


parameter_defaults:
  CeilometerStoreEvents: true
  # This section is where deployment-specific configuration is done
  # CIDR subnet mask length for provisioning network
  ControlPlaneSubnetCidr: "24"
  # Gateway router for the provisioning network (or Undercloud IP)
  ControlPlaneDefaultRoute: 192.0.2.254
  EC2MetadataIp: 192.0.2.1  # Generally the IP of the Undercloud
  # Customize the IP subnets to match the local environment
  InternalApiNetCidr: 10.99.100.0/24
  StorageNetCidr: 10.99.102.0/24
  StorageMgmtNetCidr: 10.99.103.0/24
  TenantNetCidr: 10.99.101.0/24
  ExternalNetCidr: 172.17.17.0/24
  # Customize the VLAN IDs to match the local environment
  InternalApiNetworkVlanID: 100
  StorageNetworkVlanID: 102
  StorageMgmtNetworkVlanID: 103
  TenantNetworkVlanID: 101
  ExternalNetworkVlanID: 1
  # Customize the IP ranges on each network to use for static IPs and VIPs
  InternalApiAllocationPools: [{'start': '10.99.100.111', 'end': '10.99.100.200'}]
  StorageAllocationPools: [{'start': '10.99.102.111', 'end': '10.99.102.200'}]
  StorageMgmtAllocationPools: [{'start': '10.99.103.111', 'end': '10.99.103.200'}]
  TenantAllocationPools: [{'start': '10.99.101.111', 'end': '10.99.101.200'}]
  # Leave room if the external network is also used for floating IPs
  ExternalAllocationPools: [{'start': '172.17.17.11', 'end': '172.17.17.50'}]
  # Gateway router for the external network
  ExternalInterfaceDefaultRoute: 172.17.17.1
  # Uncomment if using the Management Network (see network-management.yaml)
  # ManagementNetCidr: 10.0.1.0/24
  # ManagementAllocationPools: [{'start': '10.0.1.10', 'end', '10.0.1.50'}]
  # Use either this parameter or ControlPlaneDefaultRoute in the NIC templates
  # ManagementInterfaceDefaultRoute: 10.0.1.1
  # Define the DNS servers (maximum 2) for the overcloud nodes
  DnsServers: ["192.168.2.62","8.8.8.8"]
  # Set to empty string to enable multiple external networks or VLANs
  NeutronExternalNetworkBridge: "''"
  # NeutronFlatNetworks: '*'
  # NeutronBridgeMappings: 'datacentre:br-ex,physnet1:br-link1'
  # NeutronNetworkVLANRanges: 'datacentre:1000:1030,physnet1:100:300'
  NeutronBridgeMappings: "datacentre:br-ex,physnet0:br-link0"
  NeutronNetworkVLANRanges: "datacentre:1001:1030,physnet0:100:300"
  # The tunnel type for the tenant network (vxlan or gre). Set to '' to disable tunneling.
  NeutronTunnelTypes: 'vxlan'
  # NeutronNetworkType: 'vxlan'
  #NeutronTunnelIdRanges: "1:1000"
  # Customize bonding options, e.g. "mode=4 lacp_rate=1 updelay=1000 miimon=100"
  BondInterfaceOvsOptions: "bond_mode=active-backup"


  # Predictable VIPs
  # ControlFixedIPs: [{'ip_address':'192.168.201.101'}]
  # RedisVirtualFixedIPs: [{'ip_address':'172.16.0.8'}]
  # InternalApiVirtualFixedIPs: [{'ip_address':'172.16.200.50'}]

  PublicVirtualFixedIPs: [{'ip_address':'172.17.17.10'}]
  StorageVirtualFixedIPs: [{'ip_address':'10.99.102.10'}]
  StorageMgmtVirtualFixedIPs: [{'ip_address':'10.99.103.10'}]

